arch: CifarNet
arch_args:
  d_in: 3
  d_out: 60
batch_mode: joint
batch_size: 256
dataset: CIFAR
dataset_root: ./src/data
download: true
end_task_id: 6
epochs: 0
max_grad_norm: 100
memory_args:
  n_memorable_points: null
n_classes: 60
n_tasks: 6
optim: Adam
optim_args:
  betas:
  - 0.9
  - 0.999
  lr: 0.001
  weight_decay: 0.0
result_root: ./src/results
run_id: batch-joint_0
save_load_best_val_checkpoint: false
scale_tau_by_task_size: true
seed: 0
starting_checkpoint_run_id: batch-joint
starting_task_id: 1
test_batch_size: 256
use_ewc_weight_regularizer: false
use_experience_replay: false
use_func_regularizer: false
val_data_frac: 0.0
weight_init_mode: random
